#!/usr/bin/env bash

# ==============================================================================
# Hyprpaper & Hyprlock Multi-Monitor Wallpaper Selector & Updater
# ==============================================================================

set -euo pipefail

# --- Configuration & Paths ---
WALLPAPERS_DIRS=(
    "${HOME}/.config/hypr/wallpapers"
    "${HOME}/Pictures/Wallpapers"
    "${HOME}/Pictures/wallpapers"
)
CACHE_DIR="${HOME}/.cache/hyprpaper/thumbnails"
CONFIG_FILE="${HOME}/.config/hypr/hyprpaper.conf"
LOCK_CONFIG="${HOME}/.config/hypr/hyprlock.conf"
ROFI_GRID_THEME="${HOME}/.config/rofi/wallpaper-grid.rasi"
ROFI_THEME="${HOME}/.config/rofi/theme.rasi"

mkdir -p "$CACHE_DIR"

# --- Helper: Ensure hyprpaper is running ---
ensure_hyprpaper() {
    if ! pgrep -x "hyprpaper" >/dev/null 2>&1; then
        hyprpaper >/dev/null 2>&1 &
        sleep 0.3
    fi
}

# --- Helper: Find all wallpapers ---
get_wallpapers() {
    for dir in "${WALLPAPERS_DIRS[@]}"; do
        if [[ -d "$dir" ]]; then
            find "$dir" -maxdepth 2 -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" -o -iname "*.bmp" \)
        fi
    done | sort -u
}

# --- Helper: Generate thumbnail for an image ---
get_thumbnail() {
    local img="$1"
    local hash
    hash=$(echo -n "$img" | md5sum | awk '{print $1}')
    local thumb="${CACHE_DIR}/${hash}.png"

    if [[ ! -f "$thumb" ]] || [[ "$img" -nt "$thumb" ]]; then
        if command -v magick >/dev/null 2>&1; then
            magick "$img" -thumbnail 250x250^ -gravity center -extent 250x250 "$thumb" 2>/dev/null || cp "$img" "$thumb" 2>/dev/null || true
        elif command -v convert >/dev/null 2>&1; then
            convert "$img" -thumbnail 250x250^ -gravity center -extent 250x250 "$thumb" 2>/dev/null || cp "$img" "$thumb" 2>/dev/null || true
        else
            thumb="$img"
        fi
    fi
    echo "$thumb"
}

# --- Helper: Precache all thumbnails in background ---
cache_all_thumbnails() {
    while IFS= read -r img; do
        [[ -n "$img" ]] && get_thumbnail "$img" >/dev/null &
    done < <(get_wallpapers)
    wait
}

# --- Helper: Get connected monitors ---
get_monitors() {
    if command -v hyprctl >/dev/null 2>&1 && hyprctl monitors -j >/dev/null 2>&1; then
        hyprctl monitors -j | jq -r '.[].name'
    else
        echo "eDP-1"
    fi
}

get_focused_monitor() {
    if command -v hyprctl >/dev/null 2>&1 && hyprctl monitors -j >/dev/null 2>&1; then
        hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .name' | head -n 1
    fi
}

# --- Helper: Read current mappings from hyprpaper.conf ---
declare -A CURRENT_WALLPAPERS

load_current_config() {
    CURRENT_WALLPAPERS=()
    if [[ -f "$CONFIG_FILE" ]]; then
        local current_mon=""
        local current_path=""
        while IFS= read -r line; do
            line=$(echo "$line" | sed 's/^[ \t]*//;s/[ \t]*$//')
            if [[ "$line" =~ ^monitor[[:space:]]*=[[:space:]]*(.*)$ ]]; then
                current_mon="${BASH_REMATCH[1]}"
            elif [[ "$line" =~ ^path[[:space:]]*=[[:space:]]*(.*)$ ]]; then
                current_path="${BASH_REMATCH[1]}"
                # Expand tilde if present
                current_path="${current_path/#\~/$HOME}"
                local key="${current_mon:-default}"
                CURRENT_WALLPAPERS["$key"]="$current_path"
            fi
        done < "$CONFIG_FILE"
    fi
}

# --- Helper: Save configuration file atomically ---
save_config() {
    local tmp_file="${CONFIG_FILE}.tmp"
    {
        echo "# Hyprpaper Configuration"
        echo "# Generated by wallpaper.sh"
        echo ""
        echo "ipc = on"
        echo "splash = false"
        echo ""

        # Write each specific monitor block
        for mon in "${!CURRENT_WALLPAPERS[@]}"; do
            if [[ "$mon" != "default" && -n "$mon" ]]; then
                local p="${CURRENT_WALLPAPERS[$mon]}"
                if [[ -n "$p" ]]; then
                    echo "wallpaper {"
                    echo "    monitor = ${mon}"
                    echo "    path = ${p}"
                    echo "    fit_mode = cover"
                    echo "}"
                    echo ""
                fi
            fi
        done

        # Write fallback block if exists
        if [[ -n "${CURRENT_WALLPAPERS["default"]:-}" ]]; then
            echo "wallpaper {"
            echo "    monitor = "
            echo "    path = ${CURRENT_WALLPAPERS["default"]}"
            echo "    fit_mode = cover"
            echo "}"
            echo ""
        fi
    } > "$tmp_file"

    mv "$tmp_file" "$CONFIG_FILE"
}

# --- Helper: Set hyprlock background wallpaper ---
set_hyprlock_wallpaper() {
    local wallpaper_path="$1"
    if [[ ! -f "$wallpaper_path" ]]; then
        echo "Error: File does not exist: $wallpaper_path" >&2
        return 1
    fi
    wallpaper_path=$(realpath "$wallpaper_path")

    if [[ -f "$LOCK_CONFIG" ]]; then
        awk -v newpath="$wallpaper_path" '
        BEGIN { in_bg = 0 }
        /^[[:space:]]*background[[:space:]]*\{/ { in_bg = 1 }
        in_bg && /^[[:space:]]*path[[:space:]]*=/ {
            sub(/=[[:space:]]*.*/, "= " newpath)
            in_bg = 0
        }
        /^[[:space:]]*\}/ && in_bg { in_bg = 0 }
        { print }
        ' "$LOCK_CONFIG" > "${LOCK_CONFIG}.tmp" && mv "${LOCK_CONFIG}.tmp" "$LOCK_CONFIG"

        local thumb
        thumb=$(get_thumbnail "$wallpaper_path")
        if command -v notify-send >/dev/null 2>&1; then
            notify-send -a "Hyprlock" -i "$thumb" "Lock Screen Updated" "$(basename "$wallpaper_path")"
        fi
        echo "Hyprlock wallpaper set: $wallpaper_path"
    fi
}

# --- Apply wallpaper to monitor(s) or hyprlock ---
apply_wallpaper() {
    local target="$1"
    local wallpaper_path="$2"

    if [[ ! -f "$wallpaper_path" ]]; then
        echo "Error: File does not exist: $wallpaper_path" >&2
        return 1
    fi

    # Canonicalize absolute path
    wallpaper_path=$(realpath "$wallpaper_path")

    # If target is lock screen (hyprlock)
    if [[ "$target" == "lock" || "$target" == "hyprlock" ]]; then
        set_hyprlock_wallpaper "$wallpaper_path"
        return 0
    fi

    ensure_hyprpaper
    load_current_config

    local active_monitors
    mapfile -t active_monitors < <(get_monitors)

    if [[ "$target" == "all" || "$target" == "ALL" ]]; then
        for mon in "${active_monitors[@]}"; do
            hyprctl hyprpaper wallpaper "${mon},${wallpaper_path},cover" >/dev/null 2>&1 || true
            CURRENT_WALLPAPERS["$mon"]="$wallpaper_path"
        done
        CURRENT_WALLPAPERS["default"]="$wallpaper_path"
        save_config

        local thumb
        thumb=$(get_thumbnail "$wallpaper_path")
        if command -v notify-send >/dev/null 2>&1; then
            notify-send -a "Hyprpaper" -i "$thumb" "Wallpaper Updated" "Applied to all monitors\n$(basename "$wallpaper_path")"
        fi
        echo "Wallpaper set to all monitors: $wallpaper_path"
    else
        hyprctl hyprpaper wallpaper "${target},${wallpaper_path},cover" >/dev/null 2>&1 || true
        CURRENT_WALLPAPERS["$target"]="$wallpaper_path"
        # If no default fallback exists, set this as fallback too
        if [[ -z "${CURRENT_WALLPAPERS["default"]:-}" ]]; then
            CURRENT_WALLPAPERS["default"]="$wallpaper_path"
        fi
        save_config

        local thumb
        thumb=$(get_thumbnail "$wallpaper_path")
        if command -v notify-send >/dev/null 2>&1; then
            notify-send -a "Hyprpaper" -i "$thumb" "Wallpaper Updated" "Monitor: ${target}\n$(basename "$wallpaper_path")"
        fi
        echo "Wallpaper set on ${target}: $wallpaper_path"
    fi
}

# --- Set random wallpaper ---
set_random_wallpaper() {
    local target="${1:-all}"
    local map
    mapfile -t map < <(get_wallpapers)

    if [[ ${#map[@]} -eq 0 ]]; then
        echo "No wallpapers found in search directories." >&2
        return 1
    fi

    local rand_idx=$(( RANDOM % ${#map[@]} ))
    local selected="${map[$rand_idx]}"
    apply_wallpaper "$target" "$selected"
}

# --- Interactive Rofi Selector ---
interactive_menu() {
    ensure_hyprpaper
    load_current_config

    local active_monitors
    mapfile -t active_monitors < <(get_monitors)

    local target="all"
    local focused
    focused=$(get_focused_monitor)

    # Step 1: Prompt user for target (Monitor / All Displays / Lock Screen)
    local mon_entries="🌐 All Displays (Desktop)\n"
    for mon in "${active_monitors[@]}"; do
        local note=""
        if [[ "$mon" == "$focused" ]]; then
            note=" [Focused]"
        fi
        mon_entries+="🖥️  ${mon}${note}\n"
    done
    mon_entries+="🔒 Lock Screen (Hyprlock)\n"
    mon_entries+="🎲 Randomize All Displays\n"
    if [[ -n "$focused" ]]; then
        mon_entries+="🎲 Randomize Focused Display (${focused})\n"
    fi
    mon_entries+="🎲 Randomize Lock Screen"

    local chosen_mon_line
    chosen_mon_line=$(echo -e "$mon_entries" | rofi -dmenu -i -p "Select Target" -theme "$ROFI_THEME" || true)

    if [[ -z "$chosen_mon_line" ]]; then
        exit 0
    fi

    if [[ "$chosen_mon_line" =~ "Randomize All Displays" ]]; then
        set_random_wallpaper "all"
        exit 0
    elif [[ "$chosen_mon_line" =~ "Randomize Focused" ]]; then
        set_random_wallpaper "$focused"
        exit 0
    elif [[ "$chosen_mon_line" =~ "Randomize Lock Screen" ]]; then
        set_random_wallpaper "lock"
        exit 0
    elif [[ "$chosen_mon_line" =~ "All Displays" ]]; then
        target="all"
    elif [[ "$chosen_mon_line" =~ "Lock Screen" ]]; then
        target="lock"
    else
        # Extract monitor name
        target=$(echo "$chosen_mon_line" | awk '{print $2}')
    fi

    # Step 2: Wallpaper Picker
    local wallpapers
    mapfile -t wallpapers < <(get_wallpapers)

    if [[ ${#wallpapers[@]} -eq 0 ]]; then
        rofi -e "No wallpapers found in ~/.config/hypr/wallpapers"
        exit 1
    fi

    # Prepare Rofi Menu Entries with Icons
    local rofi_input="🎲 Random Wallpaper\0icon\x1fview-refresh\n"
    rofi_input+="📂 Browse Custom Image...\0icon\x1ffolder\n"

    # Build wallpaper list with cached thumbnails
    for img in "${wallpapers[@]}"; do
        local name
        name=$(basename "$img")
        local thumb
        thumb=$(get_thumbnail "$img")
        rofi_input+="${name}\0icon\x1f${thumb}\x1finfo\x1f${img}\n"
    done

    local rofi_theme_arg=()
    if [[ -f "$ROFI_GRID_THEME" ]]; then
        rofi_theme_arg=(-theme "$ROFI_GRID_THEME")
    elif [[ -f "$ROFI_THEME" ]]; then
        rofi_theme_arg=(-theme "$ROFI_THEME")
    fi

    local prompt_label="$target"
    if [[ "$target" == "lock" ]]; then
        prompt_label="Hyprlock"
    fi

    local selected_name
    selected_name=$(printf "%b" "$rofi_input" | rofi -dmenu -i -show-icons "${rofi_theme_arg[@]}" -p "Wallpaper (${prompt_label})" || true)

    if [[ -z "$selected_name" ]]; then
        exit 0
    fi

    if [[ "$selected_name" == "🎲 Random Wallpaper" ]]; then
        set_random_wallpaper "$target"
        exit 0
    elif [[ "$selected_name" == "📂 Browse Custom Image..." ]]; then
        local chosen_file=""
        if command -v zenity >/dev/null 2>&1; then
            chosen_file=$(zenity --file-selection --title="Select Wallpaper Image" --file-filter="Images | *.jpg *.jpeg *.png *.webp *.bmp" 2>/dev/null || true)
        fi
        if [[ -n "$chosen_file" && -f "$chosen_file" ]]; then
            apply_wallpaper "$target" "$chosen_file"
        fi
        exit 0
    fi

    # Find the corresponding image path
    local selected_path=""
    for img in "${wallpapers[@]}"; do
        if [[ "$(basename "$img")" == "$selected_name" ]]; then
            selected_path="$img"
            break
        fi
    done

    if [[ -n "$selected_path" ]]; then
        apply_wallpaper "$target" "$selected_path"
    fi
}

# --- CLI Dispatcher ---
case "${1:-}" in
    --all|-a)
        if [[ -n "${2:-}" ]]; then
            apply_wallpaper "all" "$2"
        else
            echo "Usage: $0 --all <image_path>"
            exit 1
        fi
        ;;
    --lock|-l)
        if [[ -n "${2:-}" ]]; then
            apply_wallpaper "lock" "$2"
        else
            echo "Usage: $0 --lock <image_path>"
            exit 1
        fi
        ;;
    --monitor|-m)
        if [[ -n "${2:-}" && -n "${4:-}" && "${3:-}" == "--set" ]]; then
            apply_wallpaper "$2" "$4"
        elif [[ -n "${2:-}" && -n "${3:-}" && "${3:-}" != "--set" ]]; then
            apply_wallpaper "$2" "$3"
        else
            echo "Usage: $0 --monitor <monitor_name> <image_path>"
            exit 1
        fi
        ;;
    --random|-r)
        set_random_wallpaper "${2:-all}"
        ;;
    --cache)
        echo "Generating thumbnails for all wallpapers..."
        cache_all_thumbnails
        echo "Done!"
        ;;
    --reload)
        ensure_hyprpaper
        load_current_config
        active_monitors=($(get_monitors))
        for mon in "${active_monitors[@]}"; do
            p="${CURRENT_WALLPAPERS[$mon]:-${CURRENT_WALLPAPERS["default"]:-}}"
            if [[ -n "$p" && -f "$p" ]]; then
                hyprctl hyprpaper wallpaper "${mon},${p},cover" >/dev/null 2>&1 || true
            fi
        done
        echo "Hyprpaper reloaded."
        ;;
    --help|-h)
        echo "Hyprpaper & Hyprlock Wallpaper Selector & Updater"
        echo ""
        echo "Usage:"
        echo "  $0                          Launch interactive Rofi selector"
        echo "  $0 --all <path>             Set wallpaper for all active monitors"
        echo "  $0 --monitor <mon> <path>   Set wallpaper for a specific monitor"
        echo "  $0 --lock <path>            Set wallpaper for hyprlock screen"
        echo "  $0 --random [mon|all|lock]  Set a random wallpaper"
        echo "  $0 --cache                  Pre-generate all thumbnails"
        echo "  $0 --reload                 Reload current wallpapers from config"
        ;;
    *)
        interactive_menu
        ;;
esac
