wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/images/desert.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/images/samurai.jpg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/.config/hypr/images/desert.jpg
    fit_mode = cover
}

splash = false
